---
- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Remove users from groups.
      fortios_user_group:
        vdom: "{{ vdom }}"
        state: "present" # Change 'present' to 'absent'
        user_group:
          name: "newgroup" # Specify the name of the group from which users will be removed
          member: # Specify the users to be removed from the group
            - name: "newuser"
