---
- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Remove local users.
      fortios_user_local:
        vdom: "{{ vdom }}"
        state: "absent"
        user_local:
          name: "kekeworld"
